### ISSUE TITLE
Creation of an About page

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/geonode-urbanflooding#4]
Content to be provided by @gmolinario

**Comment by simboss** [comment]
@gmolinario this is waiting on you now

**Comment by gmolinario** [comment]
@simboss yes - I'm waiting for CMU to provide me content.

**Comment by gmolinario** [comment]
hi @afabiani 

Here is the content for the about page. Thank you.

https://docs.google.com/document/d/1Q_XSBczxbhWluJ2NlD9h9RVuZ_02moRaKq7-NisKudQ/edit?usp=sharing

**Comment by afabiani** [comment]
@gmolinario Done

https://urbanflooding.geo-solutions.it/about/

**Comment by gmolinario** [comment]
Hi @afabiani  - forgot captions : 

top image: 
"A 3d model of Chiang Mai being used to communicate various policy issues with the community."

second image: 
"GIS layers overlaid and animated on top of the physical 3d model created by SPP."

third image: 
" A map of Chiang Mai's transportation system." 

fourth image: 
" A map showing Chiang Mai's residential area growth from 1989 to 2010."

**Comment by afabiani** [comment]
@gmolinario Done
